# SPDX-License-Identifier: Apache-2.0
"""tools/auto_issue_on_redundancy_degraded.py — open ``redundancy-degraded`` issues.

W5-T2 deliverable per
``Docs/stability/redundancy-sprint/05-wave5-nightly-closure.md`` §3.2.

Companion to ``check_redundancy_targets.py``: that tool emits a
``redundancy_alerts.json`` file; this tool consumes it and shells out
to ``gh issue create`` (one issue per breached scenario).

Dedup contract (W5-T2 §3.2):
  - Title shape: ``[redundancy-degraded] <scenario_id>: N/3 legs``
  - Within 24h, the same scenario_id at the same N → no new issue
    (we trust the GitHub state-open dedup as a backstop).

This tool is **read-only against the codebase**; it never writes
adapter code. It only opens GitHub issues — the *agent* (pce-autonomy)
is what reads those issues and proposes fixes.
"""

from __future__ import annotations

import argparse
import json
import logging
import shutil
import subprocess
import sys
import time
from pathlib import Path
from typing import Any, Optional

logger = logging.getLogger("pce.tools.auto_issue_on_redundancy_degraded")


# ---------------------------------------------------------------------------
# Issue body composition
# ---------------------------------------------------------------------------

def build_issue_title(alert: dict) -> str:
    sid = alert.get("scenario_id", "?")
    legs_active = alert.get("legs_active", 0)
    target = alert.get("redundancy_target", 3)
    return f"[redundancy-degraded] {sid}: {legs_active}/{target} legs"


def build_issue_body(
    alert: dict,
    *,
    health_dashboard_url: str = "http://127.0.0.1:9800/dashboard/redundancy",
    repair_hint: bool = True,
) -> str:
    sid = alert.get("scenario_id", "?")
    label = alert.get("label", "")
    tier = alert.get("tier", "")
    target = alert.get("redundancy_target", 3)
    legs_active = alert.get("legs_active", 0)
    status = alert.get("status", "")
    color = alert.get("color", "")
    phase_b = alert.get("phase_b", False)
    failed = alert.get("failed_legs", []) or []
    computed_at = alert.get("computed_at")
    when = (
        time.strftime("%Y-%m-%d %H:%M:%S UTC", time.gmtime(computed_at))
        if computed_at else "?"
    )

    lines: list[str] = [
        f"**Scenario**: `{sid}` — {label}",
        f"**Tier**: `{tier}` · **Status**: `{status}` · **Color**: `{color}`",
        f"**Legs**: `{legs_active}/{target}` "
        f"({'Phase B' if phase_b else 'Phase A'})",
        f"**Computed at**: `{when}`",
        "",
        "---",
        "",
        "## Failing / unknown legs",
        "",
    ]
    if failed:
        lines.append("| Source | Independent basis | Health | Last PASS | Last FAIL |")
        lines.append("|---|---|---|---|---|")
        for leg in failed:
            last_pass = leg.get("last_pass_ts")
            last_fail = leg.get("last_fail_ts")
            lines.append(
                f"| `{leg.get('source','?')}` "
                f"| `{leg.get('independent_basis','?')}` "
                f"| `{leg.get('health','?')}` "
                f"| {time.strftime('%Y-%m-%d %H:%M', time.gmtime(last_pass)) if last_pass else '—'} "
                f"| {time.strftime('%Y-%m-%d %H:%M', time.gmtime(last_fail)) if last_fail else '—'} |"
            )
    else:
        lines.append("_No failing legs in this snapshot._")
    lines.append("")

    if repair_hint:
        lines.extend([
            "## Recommended repair",
            "",
            "```powershell",
            f"python -m tools.repair_adapter --redundancy-degraded {sid} --json",
            "```",
            "",
            "(The repair tool maps the failing leg back to a conductor case "
            "and produces an LLM-refined patch proposal — see W5-T4.)",
            "",
        ])

    lines.extend([
        "## References",
        "",
        f"- `Docs/stability/REDUNDANCY-AUDIT-MATRIX.md` §3 (canonical state)",
        f"- `Docs/stability/redundancy-sprint/SCOPE-LOCK-2026-05-15.md` §2 (13 P0 scope)",
        f"- Dashboard: {health_dashboard_url}?scenario={sid}",
        "",
        "_Auto-generated by `tools/auto_issue_on_redundancy_degraded.py` (W5-T2)._",
    ])
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# gh CLI
# ---------------------------------------------------------------------------

def build_gh_command(
    *,
    title: str,
    body: str,
    labels: list[str],
    assignee: Optional[str] = None,
    repo: Optional[str] = None,
) -> list[str]:
    cmd = ["gh", "issue", "create", "--title", title, "--body", body]
    for lbl in labels:
        cmd.extend(["--label", lbl])
    if assignee:
        cmd.extend(["--assignee", assignee])
    if repo:
        cmd.extend(["--repo", repo])
    return cmd


def invoke_gh(cmd: list[str], *, dry_run: bool) -> dict[str, Any]:
    if dry_run:
        return {"dry_run": True, "exit_code": 0, "stdout": "", "stderr": "", "cmd": cmd}
    if not shutil.which("gh"):
        return {
            "dry_run": False, "exit_code": 127,
            "stdout": "", "stderr": "gh CLI not on PATH; install + authenticate first.",
            "cmd": cmd,
        }
    try:
        proc = subprocess.run(cmd, capture_output=True, text=True,
                              timeout=30, check=False)
    except subprocess.TimeoutExpired:
        return {"dry_run": False, "exit_code": -1, "stdout": "",
                "stderr": "gh command timed out (30 s)", "cmd": cmd}
    return {
        "dry_run": False,
        "exit_code": int(proc.returncode),
        "stdout": (proc.stdout or "")[:4096],
        "stderr": (proc.stderr or "")[:4096],
        "cmd": cmd,
    }


# ---------------------------------------------------------------------------
# Dedup helper — read existing issues to avoid duplicates
# ---------------------------------------------------------------------------

def existing_open_titles(*, label: str, repo: Optional[str] = None,
                         dry_run: bool = False) -> set[str]:
    """List currently-open issue titles with the given label."""
    if dry_run or not shutil.which("gh"):
        return set()
    cmd = ["gh", "issue", "list",
           "--state", "open", "--label", label,
           "--json", "title", "--limit", "200"]
    if repo:
        cmd.extend(["--repo", repo])
    try:
        proc = subprocess.run(cmd, capture_output=True, text=True,
                              timeout=30, check=False)
        if proc.returncode != 0:
            return set()
        data = json.loads(proc.stdout)
        return {row.get("title", "") for row in data if isinstance(row, dict)}
    except (subprocess.TimeoutExpired, json.JSONDecodeError, OSError):
        return set()


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="python -m tools.auto_issue_on_redundancy_degraded")
    parser.add_argument("--alerts", required=True,
                        help="path to redundancy_alerts.json (from check_redundancy_targets.py)")
    parser.add_argument("--label", action="append", default=None,
                        help="apply label (repeatable, default: ['redundancy-degraded','auto-detected'])")
    parser.add_argument("--assignee", default=None)
    parser.add_argument("--repo", default=None,
                        help="explicit owner/repo for `gh --repo`")
    parser.add_argument(
        "--no-dry-run", dest="dry_run", action="store_false",
        help="actually invoke `gh issue create` (default is dry-run)",
    )
    parser.set_defaults(dry_run=True)
    parser.add_argument("--quiet", action="store_true")
    args = parser.parse_args(argv)

    logging.basicConfig(
        level=logging.WARNING if args.quiet else logging.INFO,
        format="%(asctime)s [%(name)s] %(levelname)s %(message)s",
    )

    labels = args.label or ["redundancy-degraded", "auto-detected"]
    alerts_path = Path(args.alerts)
    if not alerts_path.exists():
        print(f"alerts file missing: {alerts_path}", file=sys.stderr)
        return 1
    try:
        payload = json.loads(alerts_path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        print(f"failed to parse {alerts_path}: {exc}", file=sys.stderr)
        return 1

    alerts = payload.get("alerts", []) if isinstance(payload, dict) else payload
    if not isinstance(alerts, list):
        print("alerts payload must be a list", file=sys.stderr)
        return 1

    existing_titles = existing_open_titles(
        label=labels[0], repo=args.repo, dry_run=args.dry_run,
    )

    summary: dict[str, Any] = {
        "total_alerts": len(alerts),
        "issues": [],
        "skipped_existing": [],
        "dry_run": args.dry_run,
    }
    for alert in alerts:
        title = build_issue_title(alert)
        if title in existing_titles:
            summary["skipped_existing"].append(title)
            continue
        body = build_issue_body(alert)
        cmd = build_gh_command(
            title=title, body=body, labels=labels,
            assignee=args.assignee, repo=args.repo,
        )
        result = invoke_gh(cmd, dry_run=args.dry_run)
        summary["issues"].append({
            "scenario_id": alert.get("scenario_id"),
            "title": title,
            "exit_code": result["exit_code"],
            "dry_run": result["dry_run"],
            "stdout": result.get("stdout", "")[:200],
            "stderr": result.get("stderr", "")[:200],
        })

    print(json.dumps(summary, indent=2, ensure_ascii=False))
    if not args.dry_run:
        bad = [i for i in summary["issues"] if i.get("exit_code", 0) != 0]
        if bad:
            return 1
    return 0


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
