"""PCE Core – PAC (Proxy Auto-Configuration) file generator.

Generates a proxy.pac file that routes only AI traffic through the
PCE mitmproxy instance while sending all other traffic DIRECT.

The PAC file is served by the Core API at /proxy.pac and can be
configured as the system proxy auto-config URL.
"""

import logging
from typing import Optional

from .config import ALLOWED_HOSTS, PROXY_LISTEN_HOST, PROXY_LISTEN_PORT
from .db import get_custom_domains

logger = logging.getLogger("pce.pac")


def generate_pac(
    proxy_host: str = PROXY_LISTEN_HOST,
    proxy_port: int = PROXY_LISTEN_PORT,
    extra_domains: Optional[set[str]] = None,
) -> str:
    """Generate a PAC file string.

    Combines static allowlist + custom domains + optional extra domains
    into a JavaScript PAC function.
    """
    all_domains = set(ALLOWED_HOSTS)

    # Add custom domains from DB
    try:
        all_domains.update(get_custom_domains())
    except Exception:
        logger.exception("Failed to load custom domains for PAC (non-fatal)")

    if extra_domains:
        all_domains.update(extra_domains)

    # Remove localhost entries (we don't proxy local traffic through mitmproxy)
    all_domains.discard("localhost")
    all_domains.discard("127.0.0.1")

    sorted_domains = sorted(all_domains)

    # Build the domain check conditions
    domain_checks = []
    for d in sorted_domains:
        # Use dnsDomainIs for exact match + subdomain match
        domain_checks.append(f'    if (dnsDomainIs(host, "{d}")) return proxy;')

    checks_block = "\n".join(domain_checks)

    pac_content = f"""// PCE Proxy Auto-Configuration (PAC) File
// Generated by PCE Core – routes AI traffic through local proxy
// Proxy: {proxy_host}:{proxy_port}
// Domains: {len(sorted_domains)}

function FindProxyForURL(url, host) {{
    var proxy = "PROXY {proxy_host}:{proxy_port}";

    // Never proxy localhost
    if (isPlainHostName(host) || host === "127.0.0.1" || host === "localhost") {{
        return "DIRECT";
    }}

    // AI domains → route through PCE proxy
{checks_block}

    // Everything else → direct
    return "DIRECT";
}}
"""
    return pac_content
